"""Vector store stage: build and persist a local FAISS index.

Takes the precomputed embeddings from data/processed/embeddings.json and
stores them in a FAISS vector database on disk. Because the vectors were
already generated by the embedding stage, building the index makes NO
OpenAI API calls — we pair each existing vector with its text and metadata.

The saved index is fully reusable after a restart via load_vector_store().
"""

import json
from pathlib import Path

from dotenv import load_dotenv
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings

from ingestion.config import (
    EMBEDDING_MODEL,
    EMBEDDINGS_OUTPUT_PATH,
    VECTOR_STORE_DIR,
)
from ingestion.logger import get_logger

logger = get_logger(__name__)


def _get_embedder() -> OpenAIEmbeddings:
    """Create the embeddings client the store uses to embed future queries.

    The index itself is built from precomputed vectors, but FAISS needs an
    embedding function attached so that similarity_search() can embed user
    questions at query time with the SAME model used for the chunks.
    """
    # Ensure OPENAI_API_KEY from .env is available to the client
    load_dotenv()
    return OpenAIEmbeddings(model=EMBEDDING_MODEL)


def load_embedding_records(embeddings_path: Path) -> list[dict]:
    """Load the embedding records produced by the embedding stage.

    Args:
        embeddings_path: Path to embeddings.json.

    Returns:
        List of records: {"chunk_id", "text", "page", "source", "embedding"}.

    Raises:
        FileNotFoundError: If embeddings.json does not exist (embed not run).
        ValueError: If the file is malformed or contains no embeddings.
    """
    # --- The embeddings file must exist before we can build the index ----
    if not embeddings_path.exists():
        logger.error(
            "Embeddings file not found at %s — run embed.py first", embeddings_path
        )
        raise FileNotFoundError(f"Embeddings file not found: {embeddings_path}")

    # --- Parse the JSON and validate its structure ------------------------
    try:
        with embeddings_path.open("r", encoding="utf-8") as file:
            payload = json.load(file)
        records = payload["embeddings"]
    except (json.JSONDecodeError, KeyError) as exc:
        logger.exception("Embeddings file %s is malformed", embeddings_path)
        raise ValueError(f"Malformed embeddings file: {embeddings_path}") from exc

    if not records:
        logger.error("Embeddings file %s contains no records", embeddings_path)
        raise ValueError("No embeddings found to index")

    logger.info("Loaded %d embedding records from %s", len(records), embeddings_path.name)
    return records


def build_vector_store(records: list[dict]) -> FAISS:
    """Build an in-memory FAISS index from precomputed embeddings.

    Args:
        records: Embedding records loaded from embeddings.json.

    Returns:
        A FAISS vector store containing every chunk with its metadata.

    Raises:
        RuntimeError: If FAISS index construction fails.
    """
    logger.info("Building FAISS index from %d precomputed embeddings", len(records))

    # --- Pair each chunk's text with its existing vector -------------------
    # FAISS.from_embeddings() accepts (text, vector) pairs, so no new
    # OpenAI API calls are made here.
    text_embedding_pairs = [(rec["text"], rec["embedding"]) for rec in records]

    # --- Keep chunk metadata so retrieved results are traceable ------------
    # (e.g. "this answer came from page 4 of the PDF")
    metadatas = [
        {"chunk_id": rec["chunk_id"], "page": rec["page"], "source": rec["source"]}
        for rec in records
    ]

    # --- Construct the index ------------------------------------------------
    try:
        vector_store = FAISS.from_embeddings(
            text_embeddings=text_embedding_pairs,
            embedding=_get_embedder(),
            metadatas=metadatas,
        )
    except Exception as exc:
        logger.exception("Failed to build FAISS index")
        raise RuntimeError(f"FAISS index construction failed: {exc}") from exc

    logger.info(
        "FAISS index built: %d vectors, %d dimensions",
        vector_store.index.ntotal,
        vector_store.index.d,
    )
    return vector_store


def save_vector_store(vector_store: FAISS, store_dir: Path) -> None:
    """Persist the FAISS index to disk so it survives restarts.

    Writes two files into store_dir:
        - index.faiss : the raw vector index
        - index.pkl   : the docstore (chunk texts + metadata)

    Args:
        vector_store: The FAISS store to persist.
        store_dir: Directory to save into.

    Raises:
        OSError: If the files cannot be written.
    """
    try:
        # save_local creates the directory if needed and writes both files
        vector_store.save_local(str(store_dir))
    except OSError:
        logger.exception("Failed to save FAISS index to %s", store_dir)
        raise

    logger.info("Saved FAISS index to %s", store_dir)


def load_vector_store(store_dir: Path = VECTOR_STORE_DIR) -> FAISS:
    """Load a previously saved FAISS index from disk.

    This is the reuse path: after a restart, the agent calls this instead
    of re-running ingestion/embedding.

    Args:
        store_dir: Directory the index was saved into.

    Returns:
        The loaded FAISS vector store, ready for similarity search.

    Raises:
        FileNotFoundError: If no saved index exists at store_dir.
        RuntimeError: If the index files exist but cannot be loaded.
    """
    # --- Check the index files actually exist ------------------------------
    if not (store_dir / "index.faiss").exists():
        logger.error("No saved FAISS index at %s — run build_index.py first", store_dir)
        raise FileNotFoundError(f"No FAISS index found in: {store_dir}")

    # --- Load the index -----------------------------------------------------
    # allow_dangerous_deserialization is required because the docstore is
    # pickled; it is safe here since we created these files ourselves.
    try:
        vector_store = FAISS.load_local(
            str(store_dir),
            embeddings=_get_embedder(),
            allow_dangerous_deserialization=True,
        )
    except Exception as exc:
        logger.exception("Failed to load FAISS index from %s", store_dir)
        raise RuntimeError(f"Could not load FAISS index: {exc}") from exc

    logger.info(
        "Loaded FAISS index from %s (%d vectors)", store_dir, vector_store.index.ntotal
    )
    return vector_store


def run_indexing() -> None:
    """Run the full indexing stage: load embeddings -> build -> save."""
    logger.info("=== Starting vector store stage ===")

    try:
        # Step 1: load precomputed embeddings from the embedding stage
        records = load_embedding_records(EMBEDDINGS_OUTPUT_PATH)

        # Step 2: build the FAISS index (no API calls — vectors reused)
        vector_store = build_vector_store(records)

        # Step 3: persist the index to disk for reuse after restart
        save_vector_store(vector_store, VECTOR_STORE_DIR)

    except (FileNotFoundError, ValueError, RuntimeError, OSError):
        # Specific failures were already logged where they occurred
        logger.error("Vector store stage failed — see errors above")
        raise

    logger.info("=== Vector store stage finished successfully ===")


if __name__ == "__main__":
    run_indexing()
